version: '2'
services:
    learnn-app:
        image: learnn
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://learnn-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=LearnN
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=learnn-elasticsearch:9300
        ports:
            - 8080:8080
    learnn-mongodb:
        extends:
            file: mongodb.yml
            service: learnn-mongodb
    learnn-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: learnn-elasticsearch
